# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/application
    overwrite: true

hooks:
  ApplicationStart:
    - location: bin/deploy_install.sh
      timeout: 300
      runas: root
